# Generated by Django 4.0.5 on 2022-06-19 11:47

import django.db.models.deletion

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Bar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("website", models.URLField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Beer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("price", models.IntegerField()),
                ("description", models.TextField()),
                ("specifications", models.JSONField(default=dict)),
                (
                    "bar",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="beers.bar"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BarBranch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("address", models.CharField(max_length=255)),
                ("metro", models.CharField(max_length=255)),
                (
                    "bar",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="beers.bar"),
                ),
            ],
        ),
    ]
