# Generated by Django 4.2rc1 on 2023-03-25 16:18

import uuid

import django.db.models.deletion

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Bar",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True, verbose_name="Name")),
                ("website", models.URLField(unique=True, verbose_name="Website")),
                ("updated", models.DateTimeField(default=None, null=True, verbose_name="Updated")),
            ],
            options={
                "verbose_name": "Bar",
                "verbose_name_plural": "Bars",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="Beer",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                ("price", models.IntegerField(default=None, null=True, verbose_name="Price")),
                (
                    "description",
                    models.TextField(default=None, null=True, verbose_name="Description"),
                ),
                (
                    "specifications",
                    models.JSONField(default=dict, null=True, verbose_name="Specifications"),
                ),
                (
                    "bar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="beers.bar",
                        verbose_name="Bar",
                    ),
                ),
            ],
            options={
                "verbose_name": "Beer",
                "verbose_name_plural": "Beers",
                "ordering": ("name", "bar"),
            },
        ),
        migrations.CreateModel(
            name="BarBranch",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("address", models.CharField(max_length=255, verbose_name="Address")),
                (
                    "metro",
                    models.CharField(default=True, max_length=255, null=True, verbose_name="Metro"),
                ),
                (
                    "latitude",
                    models.FloatField(blank=True, default=None, null=True, verbose_name="Latitude"),
                ),
                (
                    "longitude",
                    models.FloatField(
                        blank=True, default=None, null=True, verbose_name="Longitude"
                    ),
                ),
                (
                    "bar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="beers.bar",
                        verbose_name="Bar",
                    ),
                ),
            ],
            options={
                "verbose_name": "BarBranch",
                "verbose_name_plural": "BarBranches",
                "ordering": ("bar", "metro"),
            },
        ),
    ]
