# Generated by Django 4.0.5 on 2022-06-22 07:15

import django.db.models.manager

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("beers", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="beer",
            managers=[
                ("beer_data_managers", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name="bar",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="barbranch",
            name="address",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
