# Generated by Django 4.2rc1 on 2023-03-25 21:34

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("beers", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="barbranch",
            name="metro",
            field=models.CharField(
                blank=True, default=None, max_length=255, null=True, verbose_name="Metro"
            ),
        ),
    ]
