# Generated by Django 4.2rc1 on 2023-03-25 22:55

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("beers", "0002_alter_barbranch_metro"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bar",
            name="updated",
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name="Updated"),
        ),
    ]
