# Generated by Django 4.0.5 on 2022-06-24 06:21

<<<<<<< HEAD
from django.db import migrations, models
=======
from django.db import migrations
from django.db import models
>>>>>>> 574b7bc1525c9d3a1f77fe4fda3c0220ed8f629f


class Migration(migrations.Migration):

    dependencies = [
        ("beers", "0003_alter_beer_managers_alter_beer_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bar",
            name="updated",
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
