# Generated by Django 4.0.5 on 2022-06-24 06:21

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("beers", "0003_alter_beer_managers_alter_beer_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bar",
            name="updated",
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
