# Generated by Django 4.1.1 on 2022-09-19 09:02

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("beers", "0004_bar_updated"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="beer",
            managers=[],
        ),
        migrations.AddField(
            model_name="barbranch",
            name="longitude",
            field=models.FloatField(default=None, null=True),
        ),
    ]
