# Generated by Django 4.1.1 on 2022-09-19 09:18

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("beers", "0005_alter_beer_managers_barbranch_longitude"),
    ]

    operations = [
        migrations.AddField(
            model_name="barbranch",
            name="latitude",
            field=models.FloatField(default=None, null=True),
        ),
    ]
