repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: check-merge-conflict
    -   id: end-of-file-fixer


-   repo: https://github.com/psf/black
    rev: 22.12.0
    hooks:
    -   id: black

-   repo: https://github.com/pycqa/isort
    rev: 5.11.4
    hooks:
    -   id: isort

-   repo: https://github.com/PyCQA/flake8
    rev: 5.0.4
    hooks:
    -   id: flake8
        entry: flake8
        additional_dependencies: ["flake8-black", "flake8-builtins", "flake8-django"]

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.971
    hooks:
    -   id: mypy
        entry: mypy
        pass_filenames: false
        args: [.]
        additional_dependencies: ["django-stubs", "djangorestframework-stubs", "python-dotenv", "djangorestframework", "psycopg2-binary", 'drf_spectacular']

-   repo: https://github.com/wemake-services/dotenv-linter
    rev: 0.4.0
    hooks:
    -   id: dotenv-linter
        args: [.env_template]

default_language_version:
    python: python3.11
default_stages: [commit, push]
