version: '3'

services:
  django:
    container_name: django
    build: .
    env_file:
      - .env
    volumes:
      - .:/source/
      - static:/source/staticfiles/
      - media:/source/mediafiles/
    working_dir: /source/
    command:  bash -c "python manage.py migrate && gunicorn server.wsgi --bind 0.0.0.0:8000"
    expose:
      - "8000"
    depends_on:
      - postgres

  bot:
    container_name: bot
    build: .
    env_file:
      - .env
    working_dir: /source/
    command: python run_bot.py
    depends_on:
      - django

  postgres:
    container_name: postgres
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - "5432:5432"

  nginx:
    build: ./nginx
    volumes:
        - static:/source/staticfiles/
        - media:/source/mediafiles/
    ports:
      - "1337:80"
    depends_on:
      - django

volumes:
  postgres_data:
  static:
  media:
