version: '3'

services:
  postgres:
    container_name: postgres
    ports:
      - "5432:5432"
    image: postgres:latest
    volumes:
        - postgres_data:/var/lib/postgresql/data/
    env_file:
      - dev.env
    restart: always

volumes:
  postgres_data:
