[tool.poetry]
name = "beer_finder"
version = "0.3.4"
description = "The app will help you find the best beer for you and your friends."
authors = ["Stas Cartoon <bycs@mail.ru>"]

[tool.poetry.dependencies]
python = "^3.10"

Django = "4.1.3"
djangorestframework = "3.14.0"
drf-spectacular = "0.24.2"
psycopg2-binary = "2.9.5"
gunicorn = "20.1.0"

aiogram = "2.23.1"

requests = "2.28.1"
beautifulsoup4 = "4.11.1"

python-dotenv = "0.21.0"

[tool.poetry.dev-dependencies]
# code linters
black = "22.10.0"
isort = "5.10.1"

flake8 = "5.0.4"
flake8-black = "0.3.5"
flake8-builtins = "1.5.3"
flake8-django = "1.1.5"
flake8-isort = "5.0.3"
dotenv-linter = "0.4.0"

mypy = "0.991"
django-stubs = "1.13.0"
djangorestframework-stubs = "1.8.0"

pre-commit = "2.20.0"

# testing code
pytest = "7.2.0"
pytest-django = "4.5.2"
pytest-drf = "1.1.3"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 100
target-version = ['py310']
exclude = """
    ('
    |.idea/
    |.venv/
    |.vscode/
    ')
"""
